# Generated by Django 2.2.20 on 2021-04-09 01:55

import core.utils
import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_add_resolved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='helprequest',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(help_text='<p style="margin-bottom:5px;font-size:10px;">Seleccioná tu ubicación para que la gente pueda encontrarte, si no querés marcar tu casa una buena opción puede ser la comisaría más cercana o algún otro sitio público cercano.<br>Si tenés problemas con este paso <a href="#" class="is-link modal-button" data-target="#myModal" aria-haspopup="true">Mirá esta ayuda</a></p><p id="div_direccion" style="font-size: 10px; margin-bottom: 5px;"></p>', srid=4326, verbose_name='Ubicación'),
        ),
        migrations.AlterField(
            model_name='helprequest',
            name='picture',
            field=models.ImageField(blank=True, help_text='Si querés podés adjuntar una foto relacionada con tu pedido, es opcional pero puede ayudar a que la gente entienda mejor tu situación.', null=True, upload_to=core.utils.rename_img, verbose_name='Foto'),
        ),
        migrations.AlterField(
            model_name='historicalhelprequest',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(help_text='<p style="margin-bottom:5px;font-size:10px;">Seleccioná tu ubicación para que la gente pueda encontrarte, si no querés marcar tu casa una buena opción puede ser la comisaría más cercana o algún otro sitio público cercano.<br>Si tenés problemas con este paso <a href="#" class="is-link modal-button" data-target="#myModal" aria-haspopup="true">Mirá esta ayuda</a></p><p id="div_direccion" style="font-size: 10px; margin-bottom: 5px;"></p>', srid=4326, verbose_name='Ubicación'),
        ),
        migrations.AlterField(
            model_name='historicalhelprequest',
            name='picture',
            field=models.TextField(blank=True, help_text='Si querés podés adjuntar una foto relacionada con tu pedido, es opcional pero puede ayudar a que la gente entienda mejor tu situación.', max_length=100, null=True, verbose_name='Foto'),
        ),
    ]
